function [QBER_SH,P_sift_SH,QBER_HG,P_sift_HG]=calculateQBER_QPSK_Gamma(Attenuation,ScaleCo_SH,ScaleCo_HG,P_T_dBm,C2n) 
    P_T_W=10^(P_T_dBm/10)*10^-3;
    P_T_dBm_SH=10*log10(1/3*P_T_W*10^3);
    P_T_dBm_HG=10*log10(2/3*P_T_W*10^3);
    
    %Satellite to HAP
    P_sift_SH=jointProbabilite_QPSK_Gamma_SH(0,0,ScaleCo_SH,P_T_dBm_SH)+...
              jointProbabilite_QPSK_Gamma_SH(0,1,ScaleCo_SH,P_T_dBm_SH)+...
              jointProbabilite_QPSK_Gamma_SH(1,0,ScaleCo_SH,P_T_dBm_SH)+...
              jointProbabilite_QPSK_Gamma_SH(1,1,ScaleCo_SH,P_T_dBm_SH);
    P_error_SH=jointProbabilite_QPSK_Gamma_SH(0,1,ScaleCo_SH,P_T_dBm_SH)+...
               jointProbabilite_QPSK_Gamma_SH(1,0,ScaleCo_SH,P_T_dBm_SH);
   
    QBER_SH=P_error_SH/P_sift_SH;
    
    %HAP to Ground Station
    P_sift_HG=jointProbabilite_QPSK_Gamma_HG(0,0,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n)+...
              jointProbabilite_QPSK_Gamma_HG(0,1,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n)+...
              jointProbabilite_QPSK_Gamma_HG(1,0,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n)+...
              jointProbabilite_QPSK_Gamma_HG(1,1,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n);
    P_error_HG=jointProbabilite_QPSK_Gamma_HG(0,1,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n)+...
               jointProbabilite_QPSK_Gamma_HG(1,0,Attenuation,ScaleCo_HG,P_T_dBm_HG,C2n);
   
    QBER_HG=P_error_HG/P_sift_HG;
end